### ISSUE TITLE
Not working in Nuclide

### ISSUE THREAD

**Issue by sucrewar** [file-icons/atom#471]
Hello, 
i update to version 2.0.1 but stop work, if i downgrade to v 1.7.25 it works. 
lasted version of atom with nuclide on mac ox

**Comment by Alhadis** [comment]
Nuclide? I've not tried that.

Ugh, I wasn't even aware this program existed until now. Good grief.

I'll look into it mate.

**Comment by 401KG** [comment]
same issue, it's not working in Nuclide's file-tree,
and some kind of "can not read root..." error came out once, sry, i 4get take a pic.....

**Comment by Alhadis** [comment]
@401KG Was the `Cannot read…` error the same as the [one described here](https://github.com/DanBrooker/file-icons/issues/469)?

If so, it was fixed in v2.0.1. If not, please let me know if you encounter it again.

**Comment by Strutsagget** [comment]
Still not working in nuclide file tree. Tabbar works fine with 2.0.1

**Comment by Alhadis** [comment]
The [`nuclide-file-tree`](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-file-tree/package.json#L7) package that Nuclide installs isn't consuming Atom's file-icon service [like it should be doing](https://github.com/atom/tree-view/blob/master/package.json#L24-L30). They really need to resolve that... anybody care to send them a PR to make our future lives easier? =)

FYI, I can likely fix this with a tasteless jackhammer solution, but I'd be more comfortable knowing they're integrating with Atom properly.

**Comment by Alhadis** [comment]
> I really miss those beautiful icons :(

Can we meet halfway? Will you accept icons that look like shit? =)

<img src="https://cloud.githubusercontent.com/assets/2346707/21558852/f624c894-ce94-11e6-8913-18750c085451.png" width="265" alt="…" />

It's okay, I wouldn't either.

Think this is gonna involve a PR to Nuclide sooner rather than later...

**Comment by Alhadis** [comment]
Stop, React... please stop... they're already dead...

<img src="https://cloud.githubusercontent.com/assets/2346707/21558870/4e218c8a-ce95-11e6-849a-1be5fc516ec7.png" width="165" alt="…" />

**Comment by 401KG** [comment]
@Alhadis i never catch a sight of that error again，
and my file-tree still " look like shit"( :p) after the updating 4 v2.0.2.......

<img width="559" alt="cb5c4b02-0532-4a25-954a-2d2f9dd98df4" src="https://cloud.githubusercontent.com/assets/22787892/21559046/8d19c418-ce7f-11e6-922f-83719917fc25.png">

**Comment by Alhadis** [comment]
Glad to hear that. =) The first half of it, that is.

I released v2.0.2 without attempting to fix Nuclide because I had no way of knowing how long it would take (and I'm trying to put as many fires out as possible, as quickly as possible).

My knowledge of React/Flow is precisely zero, but I can tell at a glance it's doing some funky weird shit with adding/removing elements as the user scrolls or navigates. So, a MutationObserver clearly isn't gonna work... gonna have to think laterally here.

**Comment by 401KG** [comment]
@Alhadis thx 4 ur done and doing, man. 
i'll try 2 contact Nuclide's guys and find out if there any way 2 clear the Long term problem.

**Comment by Alhadis** [comment]
All too happy to help, mate.

Alright, this is what we'll do... we define our own icon API, and ask the Nuclide guys to use that.

Atom's file-icon API is useless. Seriously. If anybody wants to know just how much heavy-lifting this package is really doing, delete the line from `package.json` that connects it to Atom's icon-service:

```diff
diff --git a/package.json b/package.json
index 0ea3b1d..3180651 100644
--- a/package.json
+++ b/package.json
@@ -29,11 +29,6 @@
 		"tmp": "*"
 	},
 	"providedServices": {
-		"atom.file-icons": {
-			"versions": {
-				"1.0.0": "provideService"
-			}
-		}
 	},
 	"configSchema": {
 		"coloured": {
```

Then restart. Aside from tab-icons being misaligned, everything else displays fine.

Since we've pretty much already written our own damn API, we may as well formalise it.

**Comment by thierryc** [comment]
file-type-icons works with nuclide on mac ox.
This file may help you to find the solution for file-icons. 

https://github.com/lee-dohm/file-type-icons/blob/master/styles/nuclide-file-type-icons.less

**Comment by Alhadis** [comment]
Thanks, but that file's just CSS (or Less, if you will). It's simply doing what this package used to do.

Don't worry, this will be fixed. I'm just making sure the solution isn't gonna introduce more problems for anybody. :p

**Comment by thierryc** [comment]
Thank you Alhadis

**Comment by jacobmischka** [comment]
Small issue, looks like nuclide doesn't like `.icon-nuclicon-*` elements's font-family being overwritten. It looks like directories are the only elements with a class name like that. So essentially that means that any directory icon doesn't work in nuclide right now.

Please see the `.atom` directory in the screenshot below.

![virtualbox_elementary os_01_01_2017_01_47_45](https://cloud.githubusercontent.com/assets/3939997/21580549/d3886396-cfc4-11e6-9b4f-db46dc04f8d4.png)

**Comment by Alhadis** [comment]
Hrm. Could you post your current modifications to Nuclide? Need to check this locally.

**Comment by Alhadis** [comment]
It might take manual removal of the `icon-nuclicon-file-directory` class beforehand, BTW:

```js
iconSpan.classList.remove("icon-nuclicon-file-directory");
addIconToElement(iconSpan, "/home/mischka/.atom");
```

**Comment by jacobmischka** [comment]
I've still not gotten it working fully yet, but sure I'll push: https://github.com/jacobmischka/nuclide

That might work but I feel like that'll cause larger problems, I'll try it.

**Comment by Alhadis** [comment]
Weird... it's like it's only generating a maximum of 10 icons or so in the file-tree, and reusing those whenever *other* entries are listed. If that's the case, then literally nothing - icon-service or otherwise, is going to get this working reliably.

Sigh... stuff like this is why I avoid frameworks...

**Comment by jacobmischka** [comment]
Yeah, it really doesn't make much sense lol, I don't really understand why they do it this way. Hm.

**Comment by Alhadis** [comment]
Sounds like this is more an issue with their implementation, to be honest. If they're not accommodating the possibility of dynamic icons, well... there's the first major problem to fix...

It might explain the [spastic icon-morphing](https://github.com/DanBrooker/file-icons/issues/471#issuecomment-269724568) I witnessed the other day while trying the most brutally direct solution.

**Comment by jacobmischka** [comment]
Well actually I kind of see now. I haven't given up yet, I'll let you know when I have.

**Comment by jacobmischka** [comment]
Okay I actually got it working. https://github.com/jacobmischka/nuclide

For some reason it doesn't seem to be an issue anymore, nuclide's rules are taking priority now, as they should. Not sure why they weren't before though.

**Comment by jacobmischka** [comment]
This still needs some cleanup before a PR can be submitted, but I believe it works. So if anyone wants to `apm install jacobmischka/nuclide` in the meantime it should make icons work again.

I'll have to wait until tomorrow to submit the PR, I need to go to sleep now.

**Comment by Alhadis** [comment]
It's still doing that... thing for me. :<

<img src="https://cloud.githubusercontent.com/assets/2346707/21581012/c207092c-d070-11e6-8ed7-b142c7734a5b.png" width="260" alt="Figure 1" />

I hear ya on the rest factor, I'm not sure if React's still screwing with me, or I'm hallucinating...

**Comment by jacobmischka** [comment]
Hm, okay I'll take another look in the morning, thanks for letting me know.

**Comment by Alhadis** [comment]
@jacobmischka Any progress, mate? :)

**Comment by jacobmischka** [comment]
Ha, sorry. See facebook/nuclide#488 for my excuses.

**Comment by xxsnakerxx** [comment]
With `file-icons@1.7.25` everything works fine

**Comment by Alhadis** [comment]
Okay, I've worked out a stopgap. It's not perfect, but having mostly-complete support is better than nothing:

<img src="https://cloud.githubusercontent.com/assets/2346707/21801606/73f68e44-d776-11e6-8e89-920d92938249.png" width="150" alt="Right?" />

Notable limitations
---------------------------
* Nuclide's file-tree won't update its icons when hashbangs or the like have been discovered elsewhere. This may result in an odd discrepancy with what the tab-pane shows.
* The file-tree won't update to reflect changes to the package's colour settings. Users need to either restart Atom, or force icons to redraw by collapsing and expanding each root directory in the file-tree.
* Certain subsections of the file-tree won't the correct icons, such as the "Open Files" and "Uncommitted Changes" lists.
* OmniSearch won't show correct icons in its "Recent Files" list.

**Comment by jacobmischka** [comment]
Maybe it might be worthwhile to use both the old CSS method and the new JS one simultaneously. That way everyone at least gets file extension based icons, and if the new method works it takes priority.

What do you think about something like that?

**Comment by Alhadis** [comment]
I'm afraid that would require some pretty heavy rewriting of the package's core-code, which would only be temporary anyway (I hope... trying to stay optimistic here).

**Comment by Alhadis** [comment]
@jacobmischka How's it looking for you, mate? Thanks again for having a crack at fixing this. :) Hopefully FB get this sorted.

If they don't, they're probably exacting their revenge on me after I deleted my Facebook in Feb 2015 and never looked back, HAH.

**Comment by jacobmischka** [comment]
I guess maybe we should see if atom decides to make their file icon service better, but if not I feel like there's always going to be somewhere where this js solution won't work, and css might just be a nice fallback.

Still haven't had a chance to do anything else with my nuclide fork, sorry lol. Been a little busy with work, maybe later this week. They said they probably won't merge it anyway until it's discussed further, so I don't really think it's a priority anymore.

**Comment by Alhadis** [comment]
To be honest, this has nothing to do with Atom's existing file-icon service. The base issue is that Nuclide isn't using *any* service. Of course, Atom's own file-icon service isn't enough; they need the whole shebang.

GET IT?

<img src="https://media3.giphy.com/media/Cp9cUJc4hgNvG/200_s.gif" />

**Comment by Alhadis** [comment]
I am way too good at cracking myself up.

**Comment by jacobmischka** [comment]
Ha, I mean I know that. But they're much more willing to implement an official atom service than this one, if the atom one would fix the issue I think they'd be happy to include it.

I just meant, if atom changes theirs to be useful, we can require packages to support it to get the icons, but if not there's always going to be some packages that won't start using this one I feel.

**Comment by Alhadis** [comment]
**SHUT UP AND _PAY ATTENTION TO HOW HILARIOUS I AM_.**

Nah, I hear what you're saying, mate. But truth be told, I'd say Atom would prefer keeping their services generic and simple, because the spirit of the services API is to help package authors achieve things without deciding how they should be implemented.

So what we've done is really too specific and, dare I say, should be kept separate from the core APIs.

I admit I'm also a control freak who'd rather retain his grip on how this package functions. But yeah.

**Comment by jacobmischka** [comment]
That's why I think it might be worthwhile to try to maintain both the CSS and the JS solutions. It would be a lot of work though, so I can understand not wanting to take something like that on.

Version 2.0 is definitely much more powerful and very nice, but there's also something to be said for people who want a lightweight CSS solution that just works like ^1.0. I know there's another CSS-based file icons package but frankly the icons just aren't as good as this package's.

Maybe it'll just have to come down to someone releasing a fork of 1.7.25 and backporting new icons from this package.

**Comment by Alhadis** [comment]
Lightweight? Uhm.

1. Each of the dynamic strategies can be selectively disabled, and turning off modeline and hashbang strategies will disable IO output altogether, resulting in no wasted system calls

2. Startup time is improved, and there's a [readable and maintainable config](https://github.com/file-icons/atom/blob/master/config.cson) for updating icons

3. Nothing about v1's CSS was lightweight, period. Not just talking about the startup time, mind you; matching overly-qualified attribute selectors really, really, really isn't performant. Especially given how many there were... I can't imagine how badly it slowed repaint times.

**Comment by Alhadis** [comment]
Anyway, now that we have a service of our own (rather than Atom's), the key is getting Facebook to integrate it.

... we're on the same page here, right?

**Comment by jacobmischka** [comment]
Oh wow nice, I didn't realize 2.0 was more performant in addition to being more powerful. Great work then.

I just don't think they will frankly, but if we can do that that would be ideal yes.

**Comment by Alhadis** [comment]
Yeah, well, I'm a grouch when it comes to performance, probably far more so than most people. Probably for the same reason I use no transpilers or frameworks, opting instead to hand-core the barest minimum of what's needed.

**Con:** Finding a job is a nightmare
**Pro:** But hey, at least my code runs like a cut cat
**Con:** Still broke
