### ISSUE TITLE
Tree View auto hidden.

### ISSUE THREAD

**Issue by chuducty** [file-icons/atom#494]
This happen when I install this package. When I drag a folder atom or File-> Add project folder, the tree view is automatically hidden, and I have to press cmd+/ to show it

**Comment by jasonrudolph** [comment]
@Alhadis: Thank you for file-icons! Such a great addition to Atom. ✨  This particular change (cf78bc20a447373dd63ae011085ba5bc666d0983) caught me by surprise, since I personally prefer for the tree view to retain whatever state it was in when I closed the given project (i.e., if the tree view was closed when I last viewed the project, I'd prefer for the tree view to remain closed when I re-open Atom for the given project). Would you be willing to consider a pull request that provides a configuration option allowing the user to optionally configure file-icons to keep the tree view in its previous state at startup?

**Comment by Alhadis** [comment]
Sounds like a good idea, but to be honest, auto-showing the tree-view isn't even something the package should be doing. It's just a crude hack to address a bizarre regression I couldn't explain... and hopefully temporary, assuming the Atom team consider atom/tree-view#1009.

I am sympathetic, though, because I can't stand having my workspace's state tampered with, either. I **could** add support for a user setting if that's what you'd prefer. For instance, one might make the following edit to their config:

~~~diff
 "file-icons":
+	revealTreeView: false
~~~

Would that be enough?

**Comment by jasonrudolph** [comment]
@Alhadis: Thanks for the reply. :bow:


> For instance, one might make the following edit to their config:
> 
> ```diff
>  "file-icons":
> +	revealTreeView: false
> ```
> Would that be enough?

If I'm understanding correctly, I think this would be great. :zap: With this setting in file-icons, the file-icons package would simply leave the tree view alone, right? If Atom chooses to display the tree view, fine. If Atom chooses to keep the tree view hidden, also fine. Am I understanding correctly?

**Comment by Alhadis** [comment]
> If Atom chooses to display the tree view, fine. If Atom chooses to keep the tree view hidden, also fine. Am I understanding correctly?

Never mind, I've tried explaining too much.

I'll add the setting, it'll be available in the next release. Add the line to your config now to save doing so later.

**Comment by jasonrudolph** [comment]
@Alhadis: Thanks for adding that configuration option. I appreciate it! :bow:
