### ISSUE TITLE
Tree view not showing at all when adding a project folder 2.0.7

### ISSUE THREAD

**Issue by Tms157** [file-icons/atom#497]
Sorry to post again but all of the below still happening in 2.0.7

Also a new bug i think thats been caused by the last update when you open a project folder it does not open the tree view at all now you cart see the folder you just added like this: http://imgur.com/a/7ioL4 with the plugin disabled its like this: http://imgur.com/a/VYM00 if i connect to my server the tree view then shows up again (No icons tho). This just started happening after i updated. Also seems to give 'issue #433' when connecting with remote-ftp but seems to still allow me to connect not sure what that means but it does not do it when file-icons is disabled.

**Comment by Alhadis** [comment]
> when you open a project folder it does not open the tree view at all
Pressing <kbd>Cmd + /</kbd> does nothing to show the tree-view at all?

**Comment by Tms157** [comment]
Nope, cmd + / dose not show it either its the same as it was in 2.0.6. Also still does the thing with remote-ftp.

**Comment by Alhadis** [comment]
Can you show me the output of `apm list -i`?

**Comment by Tms157** [comment]
Like this? 

Remote-FTP@0.9.4
activate-power-mode@1.1.0
atom-beautify
atom-clock@0.1.2
atom-css-comb@3.1.0
atom-live-server@1.2.5
atom-material-syntax@0.4.6
atom-material-syntax-dark@0.2.5
atom-material-ui@1.3.8
atom-minify@0.7.5
atom-wordpress@0.3.0
autocomplete-paths@1.0.5
autocomplete-wordpress-hooks@0.2.2
autoprefixer@3.6.0
bleen-syntax@0.3.1
color-picker@2.2.3
css-clean@2.16.0
dark-bint-syntax@0.8.9
double-tag@0.4.0
emmet@2.4.3
file-icons@2.0.7
highlight-selected@0.11.2
linter@1.11.18
minimap@4.25.7
php-cs-fixer@4.1.0
pigments@0.37.0
remote-sync@4.1.5
sass-autocompile@0.13.2
seti-icons@1.3.4
todo-show@1.8.0
vivid-syntax@2.0.1
wordpress-dictionary@4.4.0

some of the above is disabled tho

**Comment by adamreisnz** [comment]
Hello, I am here to report the same issue. I've used package cop to narrow down that the problem is in fact caused by this package. Disabling the file-icons package makes the problem go away, and enabling it causes the tree view not to be shown when adding a project folder or opening a project using project manager. See also https://github.com/danielbrodin/atom-project-manager/issues/306 for reference.

![image](https://cloud.githubusercontent.com/assets/490562/21819162/7566cc36-d7cf-11e6-82d5-7388c9126af8.png)

![image](https://cloud.githubusercontent.com/assets/490562/21819175/85e35c28-d7cf-11e6-917e-171a1f531845.png)

Could you look into what's causing the problem? File icons version 2.0.7, on Atom 1.14.0-dev-157e8e1.

**Comment by Alhadis** [comment]
Does this still happen after upgrading to File-icons 2.0.8?

**Comment by adamreisnz** [comment]
Yep, see edit above :)

**Comment by Alhadis** [comment]
@adamreisnz Could I get you to try `a9276b1` to see if it fixes this?

Just clone from master locally into a temporary directory, run the usual linkage-steps, then reload Atom:

```shell
git clone git@github.com:file-icons/atom.git file-icons
cd file-icons
apm install .
apm link .
```

**Comment by adamreisnz** [comment]
Unfortunately still the same problem

**Comment by Alhadis** [comment]
To clarify: this only happens when `project-manager` is active, right?

**Comment by adamreisnz** [comment]
Nope, it also happens when project manager is disabled. E.g. open new window, add project folder, observe that tree is not expanded.

**Comment by Alhadis** [comment]
Okay, I see what the real problem is. Real problem is that I'm a fucking idiot who misunderstood what everybody meant when they said "Add project folder"... I forgot there was a menu command that is *literally* named **Add Project Folder**, but I thought people just meant opening a folder in another window. `/facepalm`

Other part of the issue, which is... puzzling: the `tree-view` isn't showing even after manually dispatching `tree-view:show` when invoking `application:add-project-folder`.

<img src="http://i41.tinypic.com/zk04qv.jpg" width="400" />

**Comment by adamreisnz** [comment]
Yep, *that* menu command ;)
Sorry, could have probably been clearer about that.

Have you been able to reproduce it now?

**Comment by Alhadis** [comment]
Yeah... trying to fix it. It's weird that this is happening, but I take consolation in knowing this is only a (hopefully) temporary solution. As in, this stupid mass of monkey-patched code can someday be burned.

Until then, well... hang tight I s'pose...

**Comment by Alhadis** [comment]
Okay, erm, @adamreisnz? Could you please pull from master and try again? =)

If it works, could you also run the package specs in Atom and tell me if they all pass? (You might need to run `apm install .` to install `devDependencies`).

**Comment by adamreisnz** [comment]
Yep, I'll check tomorrow.

**Comment by adamreisnz** [comment]
Looks like that works 👍

**Comment by Alhadis** [comment]
Fan-fuckin'-tastic. Just cut a patch, please enjoy.

**Comment by Prinzhillary** [comment]
this issue shouldn't be closed yet, I am still experiencing the same problems here.

**Comment by Alhadis** [comment]
Hi @Prinzhillary,

This issue was closed almost 9 months ago, and several versions of both Atom and `file-icons` have been released since then. Whatever issue you're having now is likely to be unrelated to this one.

Please submit a new issue describing the detail in depth, along with screenshots if possible. Make sure to include your version of Atom, as well as a list of packages you currently have installed (you can retrieve this by running `apm ls -lib` in a terminal, and copying what it shows).

Thanks!

**Comment by NijaahnandhRV** [comment]
Hi can anyone help me with this issue? I'm getting the same issue, ran `apm install` also still getting the same

**Atom Versions :**

```
Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
**List of packages :**

```
atom-ide-ui@0.12.0
atom-react-native-autocomplete@0.0.27
autocomplete-java@1.2.7
autocomplete-js-import@1.4.0
ide-flowtype@0.23.1
language-javascript-jsx@0.3.7
```
