### ISSUE TITLE
Incorrect icon for 'news' in filename

### ISSUE THREAD

**Issue by MaxGiting** [file-icons/atom#505]
If the filename contains the word `news` it highlights it incorrectly 
<img width="96" alt="screen shot 2017-01-06 at 13 53 08" src="https://cloud.githubusercontent.com/assets/9828591/21720054/ec2dc1d6-d418-11e6-8f8b-c8da222d880a.png">

The line affecting this is here https://github.com/file-icons/atom/blob/master/lib/icons/.icondb.js#L1085

I cannot see what needs changing because the regex is correct and it doesn't know there is a .tpl on the end.

**Comment by Alhadis** [comment]
Hey @MaxGiting,

You've actually picked up on an important oversight in the matching engine. You're right, the regex is correct, but there's much more that's going on than running through an array of expressions. Without delving too far into the internals, the matching process is controlled by [`Strategy` objects](https://github.com/file-icons/atom/tree/9cce0927a83bc50d45226640313584f16e5cba35/lib/service/strategy.js), of which the [`PathStrategy`](https://github.com/file-icons/atom/blob/9cce0927a83bc50d45226640313584f16e5cba35/lib/service/strategies/path-strategy.js) is to blame for this.

The `PathStrategy` has a feature to [strip irrelevant suffixes](https://github.com/file-icons/atom/blob/9cce0927a83bc50d45226640313584f16e5cba35/lib/service/strategies/path-strategy.js#L61-L66) from patterns before matching. This pattern is still tested, it's just tested *after* existing expressions have been checked. This is so stuff like `web-template.php.tpl` or what-have-you will show a correct icon, whilst still permitting `web-template.tpl` to show a light-bulb for Smarty templates.

What I *hadn't* factored in was the possibility that such suffixes should be tested *before* the "last resort" rules are matched (which include stuff like `*news*`, `*rc*`, etc). Now, I realise this isn't a simple fix, because the priority of a "last-resort rule" isn't output by the generator (since it's really only relevant at compile-time). However, to fix this cleanly would involve knowing where "real" rules end and best guesses begin... so I need to amend the compiler code.

Thanks for this. I apologise for the inconvenience, it was a glaring oversight on my part. Until this is fixed in the next release, you can force lightbulbs to pop up with your stylesheet:

~~~less
.icon[data-name$=".tpl"]:before{
	content: "\f0eb";
	font-family: FontAwesome;
	font-size: 15px;
	color: #d88511; // Omit this line if you're not using colours
}
~~~

**Comment by Alhadis** [comment]
HOW TO FIX SHIT, ALHADIS-STYLE
=============================

1. Swap sleep to spend literally 9 hours writing an over-the-top solution
2. Decide solution is crap and start over at 10am
3. Write a simpler solution with stinging eyes that took ~10 minutes
4. ????????
5. Get job / profit

Nah.

Anyway, fixed.

**Comment by MaxGiting** [comment]
Brilliant thank you!

**Comment by Alhadis** [comment]
My sleep-deprived pleasure!
