### ISSUE TITLE
Takes too long to load the package

### ISSUE THREAD

**Issue by cristian-sima** [file-icons/atom#508]
My atom start has become very slow.  I was wondering why and I got this

![image](https://cloud.githubusercontent.com/assets/12199042/21760502/64241440-d655-11e6-8a48-4044edaaca71.png)

which is a lot for a icon package

**Comment by Atikon** [comment]
![gi](https://cloud.githubusercontent.com/assets/5737323/21762230/da03ca96-d657-11e6-85b7-125318a14dd3.JPG)


I think it depends on the machine it runs on.

**Comment by DanBrooker** [comment]
<img width="707" alt="screen shot 2017-01-09 at 10 40 57 pm" src="https://cloud.githubusercontent.com/assets/714197/21762276/b943f37a-d6bc-11e6-8af7-bfd44c05d69c.png">

**Comment by Alhadis** [comment]
> which is a lot for a icon package

No, that's a lot for ANY package. Period. @cristian-sima, something's not right here; does this happen at *every* startup, for literally every project? Because activation time can also be influenced by the size of the project. Opening a window that uses many hundreds of icons will be unsurprisingly slower than one that has only a few files

Can you also tell us your specs? Atom version, OS, and what themes and packages you have enabled?

This is somewhat concerning, especially after the amount of effort I put in to *minimising* startup time.

**Comment by cristian-sima** [comment]
@Alhadis 


![image](https://cloud.githubusercontent.com/assets/12199042/21802452/80993c5c-d72e-11e6-9e3d-e955f1136be3.png)

yep. it seems you are right. it has something to do with my operating system. it seems that is not influenced by the project size (although I did not check for extra large with hundreds of icons).

OS: Microsoft Windows 10 Pro x64
