### ISSUE TITLE
long startup time

### ISSUE THREAD

**Issue by chrisduong** [file-icons/atom#542]
Please reduce the loading time.

Even though I love it, I have to disable it now 😢

**Comment by Alhadis** [comment]
Exactly long is it taking?

**Comment by chrisduong** [comment]
It is 75ms for MBP 2016, and 189ms for non-SSD laptop.

**Comment by Alhadis** [comment]
The state of a project determines the package's loading time: how many files are in the tree-view, how many editors are open when the program starts, etc... How large is the project you're testing with?

**Comment by chrisduong** [comment]
Thanks, maybe my project is big.

**Comment by Alhadis** [comment]
Just so you know, this package already does everything it can to keep startup time as minimal as possible - including [ahead-of-time compilation](https://github.com/file-icons/atom/blob/eb8059a0c6d5769d9c847525adad60d133ebf842/lib/icons/.icondb.js) and matching [any string once per icon](https://github.com/file-icons/atom/blob/eb8059a0c6d5769d9c847525adad60d133ebf842/lib/icons/icon-tables.js#L70-L71), with everything else outside our control. Believe me when I say there's nothing we can do to make this load any faster.

**Comment by SergioScabuzzo** [comment]
I am having the same problem with an empty window. TimeCop Package Activation shows file-icons taking 114ms to start.
What is the expected, general, activation time?

**Comment by Alhadis** [comment]
... that IS the expected general activation time. What more do you want?

Seriously, 114ms is slow for you? Some packages out there take three times that long to startup.

**Comment by SergioScabuzzo** [comment]
I was asking because I didn't know. Not to upset anybody. The comments above did not seem to relate the expected times or clarify if the given times were expected. Hence my question.
Thanks for your time and effort on this.

**Comment by Alhadis** [comment]
Sorry if I came across overly defensive: I just can't help feeling slightly miffed when people complain about a mildly-laggy startup time after spending literally *months* profiling performance to make everything as fast as possible.

So when people say things are slow, I take it as a personal failure.

**Comment by martinmanzo** [comment]
@Alhadis in my case it takes 28.000ms to load. I do have lots of files in the tree.

Just a suggestion, is there any way to just load the icons of the files that are shown in the tree?
That should improve loading time.

**Comment by Alhadis** [comment]
Are you seriously complaining about 28 milliseconds of loading time? Or did you mean to write 28 *seconds* instead?

In either case, I'm afraid the answer is "no" at this stage. However, if the delay is really giving you the shits, you can try installing and using my `tree-view` fork while waiting for Atom to review atom/tree-view#1146... assuming they're ever actually gonna do so.

Sigh... I might have to add this info to the troubleshooting docs, because I don't think the Atom team actually care enough about this...

**Comment by martinmanzo** [comment]
28000 ms (the dot is the thousand separator where I live), who would complain about 28ms?

Thanks for the response and the package.

**Comment by Alhadis** [comment]
Hahaha, save the thanks for when/if Atom merge the damn PR, because shit is going to get pretty complicated on our end if they decide to reject it.

> the dot is the thousand separator where I live

Heh. Well, to avoid confusion in future, it might be best to omit the thousands separator altogether. ;) It might've been clearer to express that in seconds, or even just `half an entire minute`. =)
