### ISSUE TITLE
Tab-icons ignoring package settings / Project Plus breaks tree-view after switching projects

### ISSUE THREAD

**Issue by gnestor** [file-icons/atom#550]
When I open Atom or switch projects (using Project Plus package), file icons display in the file tabs despite "Show icons in file tabs" = false.

**Comment by Alhadis** [comment]
Can you post a list of every package and theme you currently have active?

(I really need to get that `generate-debug-report` command setup...)

**Comment by Alhadis** [comment]
Wait, don't worry. I've installed Project Plus and can see exactly what's wrong.

I'll investigate.

**Comment by gnestor** [comment]
@Alhadis You're on top of it! Thanks 👍

**Comment by Alhadis** [comment]
Haven't had any luck locating the root of the problem, but my theory so far is it's related to some weird, idiosyncratic workspace-hackery that's enabling window-constrained project-swapping... :\

Needless to say, that's gonna make things very difficult... if any package is to perform brutal surgery on underdeveloped Atom classes, it's this one.

… see [`atom/tabs#412`](https://github.com/atom/tabs/pull/412) if my tired ramblings aren't making sense.

**Comment by Alhadis** [comment]
... would really love to know where the package is digging this shit up:

<img src="https://cloud.githubusercontent.com/assets/2346707/23389304/5e65a05e-fdbb-11e6-9859-409f3234a791.png" width="540" alt="Figure 1" />

The autocomplete suggestions just keep getting weirder as I scroll down...

**Comment by Alhadis** [comment]
@gnestor Are you able to pull the latest changes from master and confirm if [`e855849`](https://github.com/file-icons/atom/commit/e855849a812fe8cf135ba259d28f546eaf17972e) solves this for you? Before resolving the issue, I noticed the tab-icon setting updating just fine in the tab-pane.

**Comment by Alhadis** [comment]
Crap, sorry. I just realised why everything looked fine on my end: it's because I had my fork of the [`tabs`](https://github.com/atom/tabs) package devlinked with atom/tabs#412. Getting the issue again after unlinking it - yet another reminder why those PRs need to be merged.

/cc @50Wliu

**Comment by gnestor** [comment]
@Alhadis I can confirm that this is still occurring on master. Project Plus is great but actively maintained. It's good to see that you're trying to provide a legit solution with https://github.com/atom/tabs/pull/412. I'll trying checking out this PR...

**Comment by Alhadis** [comment]
Try to understand why this is happening: I had to execute some unspeakable crimes against good programming practices in order to get v2.0.0 together. What's currently in use is built upon one monkey-patched class after another... there was literally nothing I had to hook into these packages.

Trouble is, when another package author follows that same line of reasoning, you end up with crap like this.

**Comment by gnestor** [comment]
Looks good when running tabs from https://github.com/atom/tabs/pull/412 👍

**Comment by Alhadis** [comment]
Right, this is pretty awkward.

1. **The buggy tabs are my fault.**
I unknowingly introduced a regression in [`f20c23c`](https://github.com/file-icons/atom/commit/f20c23cf87c) while preparing for the PR I mentioned above. For some reason, it wasn't caught by the spec-suite (which is also concerning me). Of course, I didn't notice my fuck-up because I was keeping the fork dev-linked to catch any unexpected errors that might spring at me later.

2. **Your report actually brought a more important issue to our attention.**
The `tree-view` icons stopped updating if a user switched projects in `project-plus`. Directory icons also reverted to their defaults, which is what I quickly picked up on. So yeah, this needed to be fixed, and it might've been a while before somebody else reported it.

Guess everything happens for a reason, huh?

**Comment by Alhadis** [comment]
Gonna pause for a while to work on something much more pressing: `atom/language-javascript#495`.

**Comment by Alhadis** [comment]
Okay, so not even the fucking code was at fault here. I was just a freaking idiot and forgot about the call to Atom's old icon-service that the `tabs` package was making.

Ever felt like an idiot so many consecutive times where it's no longer funny, you just feel fucking pissed off at yourself?

Yeah, I'm wearing that colour right now.

**Comment by gnestor** [comment]
I feel you brother...But I'm glad you figured it out! I assume that I need to continue running tabs from https://github.com/atom/tabs/pull/412 until that gets merged?

**Comment by Alhadis** [comment]
Haha, eh? :D Literally nothing is required of anybody, mate. Period.

In fact, there's absolutely no reason for a regular user to worry about that PR. I shouldn't have even brought it up, it's likely confused the hell out of you.

I need to stop over-explaining shit to users, because I inevitably flow off-page into tangential subjects that obscure what the fuck I was trying to explain in the first place.

My flow-of-consciousness needs a 140-character limit.

**Comment by Alhadis** [comment]
... did GitHub's links turn blue just now, or am I seeing things? 😕

**Comment by gnestor** [comment]
Affirmative 🔵

**Comment by Alhadis** [comment]
I kinda love it when they introduce subtle site changes like this, and it becomes a psychological wrestling match between noticing when it happened, and recalling what the old one was.

At least they were courteous with dumping that big black navbar there all of a sudden. I just went "oh, okay".

Going to shut up now, because my brain's doing that "buffer overflow" thing again...
