### ISSUE TITLE
.inc files don't receive file icons

### ISSUE THREAD

**Issue by 50Wliu** [file-icons/atom#553]
Sorry, couldn't think of a good title.

Anyway, the issue is that I have a language package that overrides the PHP grammar and sets `.inc` files to Sourcepawn syntax.  This seems to be causing problems with file-icons, as they get the "blank" icon:
![image](https://cloud.githubusercontent.com/assets/2766036/23665565/d2ed862e-0326-11e7-85ae-140444ceefa8.png)
Sorry for the lack of extension, but I didn't really want to resize the tree view.

As you can see, the three `.inc` files don't receive a file icon.  The `.sp` one, however, does.  When this was first implemented in c66c14ee2f0020eba046b5c34ee90ceeee78b236, .sp was orange and .inc was green.

Manually setting the syntax to some other language and then back to SP "fixes" it (but all 4 are now orange), but then it breaks again after a while (probably has to do with switching projects and closing windows, not exactly sure).

Cache clearing did not help.

**Comment by Alhadis** [comment]
I still have no idea what these files are, or what "SourcePawn" is, but `.inc` is a really bad choice of extension. -_-

These files weren't receiving an icon because `.inc` is [treated as a faux-extension](https://github.com/file-icons/atom/blob/514b552a870290a9ae946265bb43d197c6e47fd3/lib/service/strategies/path-strategy.js#L65-L70)... meaning a file named `func.php.inc` will display PHP's icon instead of Clojure's.
