### ISSUE TITLE
Ruby spec files

### ISSUE THREAD

**Issue by TeeSeal** [file-icons/atom#570]
My ruby spec files showed up with a green ruby icon before. They aren't green anymore after the latest update. I used to find it really convenient.

What do? . _.

**Comment by Alhadis** [comment]
Use your stylesheet to change it back:

~~~less
.icon[data-name$="_spec.rb"]:before{
	font-family: "Octicons Regular";
	content: "\f047";
	font-size: 16px;
	color: #90a959;
}
~~~

Though I realised I probably should've kept the original `_spec.rb` rule when [adding new test-icons](https://github.com/file-icons/atom/releases/tag/v2.1.0#new-icons), since it matches spec-files outside of `spec`/`test` directories...

**Comment by TeeSeal** [comment]
Thank you ^^
