### ISSUE TITLE
Invoking `tree-view:show` by file-icons unwantedly take away focus from select-list

### ISSUE THREAD

**Issue by t9md** [file-icons/atom#594]
I want to share the issue the user of my package([project-folder](https://atom.io/packages/project-folder)) recently reported.

https://github.com/t9md/atom-project-folder/issues/9#issuecomment-298818941

- This issue does not happen when file-icons was not installed.
- This issue happens when user started atom with empty project-list and added very first project-folder manually after atom started.

### Summary of issue.

- My package project-folder(it's package name) allow continuously add/remove project-folder by hitting `space` on `select-list`.
- Items on select-list are project-folders to add/remove.
- I know I use select-list a bit strange way but this is important for this package to allow keyboard based quick project-folders manipulation.

- When file-icons was installed, very first `add` project-folder cause `select-list` closed where expected to keep opened.
- The reason is when very first project-folder was added, file-icon invoke `tree-view:show` to reveal tree-view.
- Which take away active focus from project-folder's `select-list` to `tree-view`'s element( this is unwanted behavior ).
- Setting `file-icons.revealTreeView` to `false` solve problem, usable as workaround.
- But even after applying workaround, I still see following diff
  - with `file-icons` installed: tree-view become visible when I close `select-list`.
  - without `file-icons`: tree-view immediately become visible (although it's difficult to see since it's blured ) while focus is still  on `select-list`.

I investigated and now I know why you added this.

https://github.com/file-icons/atom/commit/b6f1a4f7a683066735987ecd29b4da8449800cca

My request and questions are

- Request
  - Make `file-icons.revealTreeView` available from settings-view. so that user can easily find.
  - Hopefully want this to be default `false`. so that my package and other package not get focus taken-away by file-icons.( I know this is still rare situation )
- Question
  - Revealing treeView by `file-icons` side is necessary? Without installing file-icons, adding project via `atom.project.addPath(dirPath)` automatically shows tree-view panel.

**Comment by Alhadis** [comment]
[Seems like you fixed this](https://github.com/t9md/atom-project-folder/issues/9#issuecomment-298843875). After installing your package, I couldn't see anything that was wrong, so I guess this is a non-issue.

> Make `file-icons.revealTreeView` available from settings-view. so that user can easily find.

Sorry, no. It's already bad enough that we're tampering with the `tree-view` package. It's even worse we're forcing it to open by itself (when users reported the tree-view stopped opening when they opened a new project - and the reasons why are still a mystery). This "setting" was a last resort because some users wanted the `tree-view` to stay hidden at startup.

Now, the hack is (hopefully) only temporary. One a certain pull-request is reviewed and merged by the Atom team, all this hacky behaviour will go away and the auto-open problem will be fixed.

That's the reason I'm not making this visible in the package's settings panel. That, and it's not a setting that's related to icons. It isn't even a setting - it's a **hack**.

I hope I've made things clearer for you.

**Comment by t9md** [comment]
> Now, the hack is (hopefully) only temporary. One a certain pull-request is reviewed and merged by the Atom team, all this hacky behaviour will go away and the auto-open problem will be fixed.

That's good news.

For the fix I made on my package, it's also hack to workaround issue introduced by file-icons.

To clarify, what I wanted you to tell is, installing file-icons introduces slight behavioral changes when adding very first project folder by `atom.project.addPath(dirPath)`.
That possibly affect other package like my atom-project-folder package.

I'm not asking you to fix, since I workaround by my side.
Just want to share the what and why happened because I thought you interest it.

**Comment by Alhadis** [comment]
No. Too many people complained about the `tree-view` not opening when they added a project folder. It's quite clear that the majority of users expect this behaviour, so I'm sorry, but this isn't changing.
