### ISSUE TITLE
Update in atom failed

### ISSUE THREAD

**Issue by HowlNox22607** [file-icons/atom#609]
I need to reinstall the package by the terminal, else i got a 503
![image](https://cloud.githubusercontent.com/assets/18665917/26633172/80d960ae-45e0-11e7-85cd-d6b1abb52b39.png)

**Comment by Alhadis** [comment]
@HowlNox22607 A status code of 503 indicates the responding server wasn't able to... well, respond. See Wikipedia's page for [HTTP status code definitions](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes):

> **503 Service Unavailable**  
> The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state.

In other words, you should be able to try again, because this sort of issue has nothing to do with the package.

If you're still unable to complete the installation, delete the `~/.atom/.apm` directory and try reinstalling.

Finally, if that *still* hasn't worked (which is unexpected), please reinstall by running the following commands in your terminal:

~~~bash
(apm install --verbose --production file-icons) >feedback.log 2>&1
[ $? -eq 0 ] && echo "Install succeeded" || echo "Failed to install"
~~~

Unless you see `Install succeeded` in the output, you'll end up with a very large log file named `feedback.log` containing detailed error diagnostics. Upload it to [PasteBin.com](https://pastebin.com/) or as a [Gist](https://gist.github.com/). Once uploaded, paste the URL as a comment to this issue.

I doubt things are so bad that they get to this point, however.

**Comment by HowlNox22607** [comment]
I know its just we can't access the server inside of Atom, we need to do it on the terminal
