### ISSUE TITLE
my perl scripts has an onion icon instead of the camel!

### ISSUE THREAD

**Issue by toshirov** [file-icons/atom#640]
In previous versions of this plugin the icon selected was correct (Perl camel) ... now it's wrong.

<img width="703" alt="captura de pantalla 2017-08-16 a las 15 13 32" src="https://user-images.githubusercontent.com/3130050/29364958-90518dbc-8295-11e7-9d2c-8041f41aa678.png">

**Comment by Alhadis** [comment]
See 0689c3118ceb506969f3380f438db3ac7c33a945.

**Comment by prvst** [comment]
I second that! The onion os not a representation of the Perl language itself, the O'Reilly's Camel is. As you can see [here](http://www.perlfoundation.org/perl_trademark), the onion is a trademarked symbol for the [Perl Foundation](http://www.perlfoundation.org/), a group dedicated to promoting the language.

**Comment by Alhadis** [comment]
@prvst What difference does that make? The camel is also a trademark, and it's also a trademark of O'Reilly Publishing, who have less to do with Perl than the Perl Foundation do.

Unlike Python, there isn't one "truly official" logo for the Perl language. If you prefer camels instead of onions, change it using your stylesheet.
