### ISSUE TITLE
Atom does not start, I am using windows 10

### ISSUE THREAD

**Issue by VivasRubio** [file-icons/atom#645]

**Comment by Alhadis** [comment]
I'm assuming you mean that installing this package has caused Atom to stop working for you. Is that it?

You'll need to be more specific when you say _"stop working"_, because that could mean a number of things. How has Atom "stopped working" for you?

It would also be helpful if you provided a list of installed packages and themes. Can you run the following command in your shell, and copy+paste the list it generates?

~~~console
$ apm ls -bi
~~~

**Comment by VivasRubio** [comment]
Atom just stop working, I ignore why....... does not start at all.

**Comment by Alhadis** [comment]
Have you tried uninstalling and reinstalling, to see if that helps?

You still need to tell us what packages you're using, in case one of them has conflicts with another.

**Comment by VivasRubio** [comment]
Hi, this is the screen shot...

https://snag.gy/2je1BU.jpg

also, I uninstall the program and installed again, and the problem persists... is a windows 10 problem , i dont know how to fixed

**Comment by Alhadis** [comment]
You're still not telling us *how* the program is failing to start. What exactly do you *see* when you try starting Atom? An error message? Nothing at all? Does it manage to show even a window at least?

**Comment by Alhadis** [comment]
@VivasRubio I was trying to help you, dude. Deleting all your comments and giving the maintainer a 👎 instead of an answer is a seriously immature, bizarre response.

Try filing a report at the [Atom repo](https://github.com/atom/atom/issues) if you feel this problem isn't package-related (I don't). But if you're gonna submit another issue here, do so with helpful information included. Not doing so will of course lead to the maintainer asking for more info.
