### ISSUE TITLE
Split this plugin

### ISSUE THREAD

**Issue by WaKeMaTTa** [file-icons/atom#648]
Hello,

Can plugin is :cool: but this metrics is not :cool: :

![image](https://user-images.githubusercontent.com/3450257/30643747-748784d8-9e10-11e7-863c-9cf9b9a2e042.png)

Can we split this plugin in to many plugins.

Example:

- `file-icons` the minimum / the base
- `file-icons-office` (requires `file-icons-base`) this have icons like: pdf, doc, docx, odt, txt, ...
- `file-icon-web` (requires `file-icons-base`) this have icons of web: javascript, html, css,
- `file-icon-dinamic-css` (requires `file-icons-base`) this have icons of web: sass, scss, less, ...
- ...

**Comment by Alhadis** [comment]
Hi @WaKeMaTTa,

The number of icons and formats actually has very little impact on loading time. The slow activation time is the fault of certain implementation decisions that were made to overcome shortcomings in Atom's APIs. 

Splitting `file-icons` into separate icon-related packages simply isn't going to happen. It would be messy and difficult to maintain, and would probably also require some ugly refactoring of the codebase. Furthermore, any improvement to startup time would be negligible at best, and slower at worst (due to the time it takes to load multiple packages, should users have many installed).

Consult and subscribe to #565 for details and updates about the slow loading time.
