### ISSUE TITLE
Codekit icon cuts a little bit

### ISSUE THREAD

**Issue by orsileonel** [file-icons/atom#676]
Hey! First of all thanks a lot for this fantastic package and the effort you put on it! 🎊

I just wanted to let you know that the **Codekit icon** cuts a little bit on the left edge, not big deal but reporting the small issue just in case:

<img width="141" alt="screen shot 2017-11-21 at 14 50 05" src="https://user-images.githubusercontent.com/7152955/33058766-2d38dc02-cecc-11e7-8c1b-cf74f226ecac.png">

I'm using **Atom (1.22.1 x64) on macOS High Sierra (10.13.1)**.

Keep up the awesome work! 😃

**Comment by Alhadis** [comment]
Thanks for the kind words! 😀

I can't reproduce this oddity on my end, but it does occur when I set my theme to Atom Material. Within the `tree-view`, at least; Atom-Material's tab-pane seems fine.

<b>Atom Dark UI:</b> <img src="https://user-images.githubusercontent.com/2346707/33070835-72bb5d5e-cf0d-11e7-82e1-a74069fcb10e.png" hspace=10 alt="Figure 1" valign="middle" />

<b>Atom Material:</b> <img src="https://user-images.githubusercontent.com/2346707/33070841-77863db8-cf0d-11e7-8f79-d06b4660dadd.png" hspace=10 alt="Figure 2" valign="middle" />

Since it's a styling issue, you can easily fix this [with your stylesheet](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks):

~~~css
.codekit-icon::before{
	left: 1px;
}
~~~

**Comment by orsileonel** [comment]
Ah ok, sorry about that, I thought it may come from the package the issue! I'm using the theme **Chester Atom**, will fix it touching the CSS, although it's something small.

I think you can close the issue 🙂

Thanks again! 😃
