### ISSUE TITLE
Icon Offsets

### ISSUE THREAD

**Issue by carlesjavierre** [file-icons/atom#703]
On the [/styles/icons.less](https://github.com/file-icons/atom/blob/master/styles/icons.less) file, there are several (if not all) "top" css values are not being applied correctly. All the icons have an offset of 1 or 2 pixels. I've tried with "margin-top" instead of "top", and works (not really a good fix but so you know it's happening)

**Comment by Alhadis** [comment]
Hi @carlesjavierre, could you elaborate on what themes you're using, please? This is obviously a styling issue, and I suspect the theme might be forcefully overriding the offset using `top: auto !important;` or something similar.

**Comment by carlesjavierre** [comment]
Hello @Alhadis, I am currently using the (maybe new?) default theme, "One Dark", since the Atom Dark burns my eyes. I guess that's something related to the 

%localappdata%\atom\app-1.23.3\resources\app.asar\node_modules\one-dark-ui\index.less

```
.list-group .icon::before, .list-tree .icon::before {
    top: initial;
    line-height: inherit;
    height: inherit;
    vertical-align: top;
}
```

That's the only thing I've seen that is forcing icons to be moved. By disablind the "top: initial" everything moves down and gets centered (maybe the folders get excessively down, but the rest gets on point)

**Comment by Alhadis** [comment]
I think more people would complain if we overrode the `one-dark` theme's styling, especially since the offsets were only being applied in the first place to fix stuff like `top: 1px`.

The icons look fine in the `one-dark` and `one-light` themes, so I'm gonna close this as a non-issue. If you still prefer the `top` property be removed, I suggest forking the theme and linking it locally instead:

~~~console
λ apm link /path/to/one-dark-ui/
~~~
