### ISSUE TITLE
Support for .prettierignore file

### ISSUE THREAD

**Issue by AlecRust** [file-icons/atom#718]
What do you think about using the Prettier logo (or a faded version like ESLint) for `.prettierignore` files?

![screenshot](https://i.imgur.com/fcxZrA6.png)

**Comment by Alhadis** [comment]
Seems like a good idea. You wanna file a PR for this or should I do it? 😉

I don't use Prettier, so there might be other Prettier-relevant filenames I'm completely oblivious of.

**Comment by AlecRust** [comment]
Happy to look at it, new to this project though. For example are there any colour shading rules around primary (`eslintrc.json`/`.prettierrc`) vs secondary (`.eslintignore`/`.prettierignore`) config file icons like the above screenshot might suggest?

**Comment by Alhadis** [comment]
Nope. Generally, we use colours used by the icon's official branding. Additional filetypes using that icon tend to vary in that shade simply because they're colours pulled from the icon's styleguide. Since the project's [colour palette](https://github.com/file-icons/atom/blob/master/styles/colours.less) is limited to ~27 swatches, there's only so much variation of icon-colours we can do before shit just gets fully-random. 😅
