### ISSUE TITLE
TypeError when installing

### ISSUE THREAD

**Issue by goswami-rahul** [file-icons/atom#723]
This error comes up when I try to install from `apm install file-icons`
```
Installing file-icons to /home/deadpool/.atom/packages /usr/share/atom/resources/app/apm/lib/install.js:313
          if (body.releases.latest) {
                           ^

TypeError: Cannot read property 'latest' of undefined
    at /usr/share/atom/resources/app/apm/lib/install.js:313:28
    at Request._callback (/usr/share/atom/resources/app/apm/lib/request.js:56:22)
    at Request.self.callback (/usr/share/atom/resources/app/apm/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)

```

**Comment by Alhadis** [comment]
Looks like a botched attempt to load JSON, which can happen if somebody's connection drops out (which could've been yours, or that of a CDN server somewhere that shat itself).

Try again, and if it produces a similar error, you might need to wipe `apm`'s download cache to get rid of a corrupted package download:

~~~shell
rm -rf ~/.atom/.apm
~~~

Then try again. If that *still* doesn't work, well... then we have an issue on our hands...

**Comment by goswami-rahul** [comment]
@Alhadis sorry for the late reply.
I tried your instructions 

> rm -rf ~/.atom/.apm
> apm install --production file-icons

but unfortunately I still get the same error as I mentioned above :(
And I don't think its problem with the internet because I just installed some other packages for Atom as well, with no errors.

**Comment by Alhadis** [comment]
Weird. You're best off reporting this to [`APM repository`](https://github.com/atom/apm/issues), because this has nothing to do with the package's code. In fact, we don't have any power over how `apm` installs and publishes packages, it's all controlled by `atom.io`'s infrastructure.

In the meantime, install this package directly without `apm`:

~~~shell
cd ~/.atom/packages
rm -rf file-icons
git clone https://github.com/file-icons/atom.git file-icons
cd file-icons && npm install --no-save --no-package-lock .
~~~

I'm sorry you're having these troubles.

**Comment by kumarsreenivas051** [comment]
Alhadis thanks man for your instructions. It worked smoothly in my machine.
