### ISSUE TITLE
Add icon for firestore.rules

### ISSUE THREAD

**Issue by angrykoala** [file-icons/atom#726]
`firestore.rules` file, as generated by [firebase cli](https://firebase.google.com/docs/firestore/security/get-started) doesn't have an icon.

It should display the same icon as `.firebaserc` or `firebase.json`

**Comment by Alhadis** [comment]
What syntax do these files use? They seem to be using some [custom data format](https://github.com/pinarx/firebase-js-sdk-integration-tests/blob/7a23ec5f03dbbafe1b16af596bff1e66cc3b7b7e/config/firestore.rules)?

**Comment by angrykoala** [comment]
Yes they use a javascript-like sdl, [this atom package](https://atom.io/packages/firestore-rules-grammar) adds support for this format

**Comment by Alhadis** [comment]
Entiendo, gracias! =)

I was asking because this data format should also be represented on GitHub, going by the number of [`firestore.rules`](https://github.com/search?q=filename%3Afirestore.rules+NOT+nothack&type=Code) files in-the-wild (~2,073 so far). Do all these files have names of `firestore.rules` or `firestore.rule`, or can the filename vary (e.g., `foo.rules`, `bar.rules`), etc

**Comment by angrykoala** [comment]
afaik it could be any *.rules file, but the de facto standard is firestore.rules (at least for firestore). I haven't seen *.rule yet

**Comment by Alhadis** [comment]
Okay, thank you! 😀That'll give me enough knowledge to go by to prep a pull-request for GitHub Linguist. Support for `firestone.rules` in Atom itself has now been [catered for](https://github.com/file-icons/atom/commit/61459186e80a117dc2150b05863b04d7af27d7e7).
