### ISSUE TITLE
Toggle presence in various sections

### ISSUE THREAD

**Issue by sandstrom** [file-icons/atom#731]
Thanks for an awesome plugin! 🏆 

AFAIK the icons can be present in three locations:
1. Tree / project viewer
2. Tabs
3. Search hits

Would be neat if it was possible to toggle them on/off in all three instances. Right now one can only toggle them on/off for the tabs.

**Comment by Alhadis** [comment]
:wave: Hey @sandstrom,

One can use CSS to selectively hide icons in various panes:

~~~less
/* Tree-view / project viewer */
[is="tree-view-file"] > .icon::before{
	content: none;
}

/* Fuzzy-finder (Search hits) */
.fuzzy-finder{
	.icon::before{
		content: none;
	}
	
	.list-group .no-icon,
	.list-tree .no-icon{
		padding-left: 0;
	}
}
~~~

The tab-pane setting is a carryover from the package's past: In v1 of `file-icons`, virtually *everything* was [pure CSS](https://github.com/file-icons/atom/blob/v1.7.25/styles/file-icons.less). The tab-pane setting was for toggling a class on the `<body>` element, one which controlled whether tab-icons were displayed or not. v2 introduced a more programmatic approach, but retained the tab-icon setting primarily for user convenience.

Now, I'm not adverse to adding package settings to control the display of `tree-view` and `fuzzy-finder` icons. However, there'd need to be sufficient demand from users to justify the added complexity. Since this doesn't come up too often, and because CSS is the recommended way of customising how/where/if icons are displayed, I don't foresee this ever happening.

**Comment by Alhadis** [comment]
Alright, gonna close this as a `wontfix`, as I believe CSS is sufficient enough to selectively hide icons inside specific UI elements. Given lack of demand from users requesting this feature, I don't believe it would be worth the complexity of implementation.

Anybody who feels differently is more than welcome to share their thoughts in this thread.

**Comment by sandstrom** [comment]
@Alhadis I understand, although this is something I'd like, I agree that it doesn't make sense to build it if I'm the only one who've asked for it so far.

Anyway, great addon! 💯

**Comment by Alhadis** [comment]
Thanks man, the kind words are appreciated. Seriously.
