### ISSUE TITLE
Erlang: icon colors are too similar to each other.

### ISSUE THREAD

**Issue by zaroth** [file-icons/atom#735]
One picture is worth a thousand words:

![2018-05-15_16-44-56](https://user-images.githubusercontent.com/840021/40064203-510dc26a-585f-11e8-9563-042d513c20e6.png)

I'm not colorblind, but I have serious trouble with distinguishing the colors of `.beam`, `.erl` and `.hrl` at the first glance. This is especially troublesome with `.beam` and `.erl` files, which usually have the same filename produced by the compiler, and `.beam` files are basically binary and you don't want to open them in Atom, ever.

I included `.py` and `.pyc` in the screenshot. That's because IMHO `.beam` files, being binary, could maybe use a similar, very distinguishable at a glance icon as binary `.pyc` files. They fulfill a similar role in Python language.

**Comment by Alhadis** [comment]
FWIW, I actually *am* colourblind, and I'm total agreement with you. :|

However, icon shapes and icon colours are represented independently using CSS classes. Customising the shades of red/brown/whatever for Erlang icons *specifically* is easily done. Add something like this to your stylesheet:

~~~less
.erlang-icon {
	&.medium-red::before    { color: #ea3a3c; }
	&.dark-red::before      { color: #a22c2e; }
	&.medium-maroon::before { color: #8f5536; }
	&.dark-maroon::before   { color: #8f5536; }
	// Etc …
}
~~~

[Here are the lines](https://github.com/file-icons/atom/blob/2826d399428397d29822734dd68887e9cb582927/config.cson#L1503-L1514) in `config.cson` which define the colours for each Erlang-related file extension. 

Now... me recommending this as a fix isn't a case of *"hurrr, I'm too lazy, fix it yourself"*. It's because colours and contrast will vary drastically between users and their choice of ui-theme. What you're using now has worse contrast than, say, `seti-ui`, where a pitch-black background pronounces such colours better:
<img width="191" alt="Figure 2" src="https://user-images.githubusercontent.com/2346707/40065210-942f5ec4-58a4-11e8-9941-67814b76e081.png">

The complications of adding icon-specific colour tweaks is best left as an exercise to end-users, because if we started adding such adjustments for icons – for *all* users, we'd be drowning in monolithic stylesheets full of very subjective adjustments.

As I said, I *am* colourblind (not in the red/brown spectrum though 😉) so I know from personal experience how terribly subjective people's opinion of colours can be.

(For the record, pink sucks and yellow is gross. There, I said it. 😀)

**Comment by zaroth** [comment]
@Alhadis 
While I agree with your sentiment of leaving the customized tweaking to the end-users, I'm also a very strong proponent of _sane defaults_. That's because default settings _rule the world_:

- http://digg.com/2016/default-settings
- https://www.theguardian.com/technology/2013/dec/01/default-settings-change-phones-computers
- https://uxplanet.org/the-power-of-defaults-992d50b73968

I'm an example of that here. If I had installed a custom Atom theme, I would instantly take your advice, hell, I wouldn't have even bothered to create this issue in the first place. But no - this is me using the default Atom theme (fresh Windows install) with the default file-icons settings, being almost completely unable to distinguish at a glance a _source code_ icon from a _binary_ icon. Is it the out-of-the-box experience we want to present to our end users by default? 😅

**Comment by zaroth** [comment]
While I don't really understand your hostility here, I do understand that you're against this idea and respect your decision. Thanks for the pointers.

**Comment by Alhadis** [comment]
That "hostility" is simply my annoyance at having you condescend to me on the topic of UX and program design, as though the links you posted are something that's somehow beyond my comprehension.

There's also nothing to "fix" upstream. It's subjective. Some people might find the icons too uniform, and most people might prefer icons that look much flashier. That doesn't make it a bug.

**Comment by Alhadis** [comment]
> So my issue was never with tweaking how the colors themselves look, but with the choice of colors for Erlang files themselves...

Alright, *that* would have come across a whole lot differently if you'd stressed that earlier.

Generally, I try to pick colours which match those of a logo's branding or the branding's official styleguide. That doesn't always leave me rich with options, so the colours I end up choosing are usually "analogous": that is, close-by on the colour wheel: For orange, that'd be red and yellow, possibly maroon. For blue, often cyan or purple, with an appropriate level of pitch (dark purple tends to flow nicely with dark red and shades of blue, anyway, I digress).

I won't lie: I know fuck all about Erlang, or what `.beam` files are (I'm assuming those `.beams` aren't light-related, right? 😉) When I googled, every Earl I came across was reddish-brownish-maroonish. Earlang is a red dude, and yeah, that's the extent of my rationale for monotonous colours. :D

Sometimes I *do* just resort to a truly random colour, because there are more XML-derived file formats in the world than there are visible wavelengths of light. 😀

**Comment by Alhadis** [comment]
FYI, the `file-icons` package is already adjusting colours for certain icons because their details are too faint to comfortably make out on certain backgrounds. That was my idea, and I felt @ahmadseleem's pain in #168 because I myself had a light-coloured UI theme. So there's already some motif-sensitive corrections that take place. :)
