### ISSUE TITLE
Linux error

### ISSUE THREAD

**Issue by Perkles** [file-icons/atom#755]
npm ERR! Linux 4.15.0-32-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/zuryk/.atom/.apm/.apmrc" "--userconfig" "/home/zuryk/.atom/.apmrc" "install" "/tmp/d-118722-10934-2x0w3e.ut3vm42t9/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118722-10934-1fxdkuw.urbmlsor/npm-debug.log

**I get this error when i try to download, both inside Atom or command line**

**Comment by Alhadis** [comment]
It says in the error output that the issue is related to connectivity. Go to Atom's general settings panel, and look for a setting at the bottom of the page reading something like **"Use Proxy when connecting with APM"**.

It might help if you wipe out the locally cached package downloads too (`~/.atom/.apm/`). This will clear any botched or corrupted downloads that might impact redownloading.

However, I don't have any control over how packages are distributed by APM or NPM, and since your problem appears to be connectivity, you're better off bringing this up on one of their ends. :wink:
