### ISSUE TITLE
Husky

### ISSUE THREAD

**Issue by jacobbuck** [file-icons/atom#766]
Would be great to have an icon for [husky](https://github.com/typicode/husky) configuration files: `.huskyrc`, `.huskyrc.json`, `.huskyrc.js` 🐶

**Comment by Alhadis** [comment]
I was wondering this myself recently. Husky doesn't appear to have a project logo, however. The 🐶 emoji is used, but emoji tend not to make great icons because their appearance varies across systems (not to mention they're impossible to recolour with CSS).

I'm wondering if we shouldn't add a black-and-white emoji font (like [Noto Emoji](https://github.com/googlei18n/noto-emoji#bw-emoji-font)) for cases like this. What do you think?

**Comment by jacobbuck** [comment]
Yeah I too was thinking a variation of the 🐶 emoji, and Noto Emoji looks good 👌

**Comment by jacobbuck** [comment]
Alternatively something like this from Noun Project https://thenounproject.com/search/?q=dog%20face&i=703107

**Comment by Alhadis** [comment]
I think a drawing of a real husky works better. 👍

<img src="https://user-images.githubusercontent.com/2346707/47198096-1420c280-d3b6-11e8-8bd7-8d998158185d.png" width="360" alt="Figure 1: Husky" />

**Comment by JimiC** [comment]
@Alhadis Is it on if we use your `husky` icon in [vscode-icons](https://github.com/vscode-icons/vscode-icons/issues/1731)?

**Comment by Alhadis** [comment]
Be my guest! :wink:

(and oops, didn't mean to reopen this... stupid phone)
