### ISSUE TITLE
Error: Cannot find module 'mapped-disposable'

### ISSUE THREAD

**Issue by NeutronFury54** [file-icons/atom#770]
Apparently cannot build without

**Comment by Alhadis** [comment]
Where are you seeing this? In the typical error message displayed in a top-right panel?

This usually indicates that there was a timeout while waiting for dependencies (or the package itself) to finish downloading. Under `~/.atom/packages/file-icons/node_modules/`, you should have a module named [`mapped-disposable`](https://github.com/file-icons/MappedDisposable). 

Delete the contents of that directory, and try doing a manual install of the missing module using NPM:

~~~console
λ cd ~/.atom/packages/file-icons/node_modules/
λ rm -rf mapped-disposable
λ npm install --no-save mapped-disposable
~~~

Then restart Atom. Does that help?

**Comment by NeutronFury54** [comment]
Yes, the error message appears as a red extra pop-up in the upper right-hand corner. 
I don't know how to access the directory you've noted; I'm using windows, and the PROS terminal doesn't even open. 
If what you've described uninstalls and re-installs the module, I've tried multiple times to no avail, though perhaps you could describe what you mean by this? 
Thanks for your help

**Comment by Alhadis** [comment]
Sounds like there's a corrupted download being cached somewhere. I'm not familiar with PROS (though I've heard of it), but assuming it uses Atom's package manager, there should be a directory named `.apm` located inside `C:\Users\%USERNAME%\.atom` or `C:\Users\%USERNAME%\.pros-atom` (replace `%USERNAME%` with whatever your usual login name is). Try deleting it, then reinstalling.

I'm sorry I can't be of much more help than this. Sometimes Atom's package registry times out when installing or updating a package, leaving users with an incomplete download stuck in their cache. It's not something I have any control over, I'm afraid. 😞 Timeouts are probably more frequent with `file-icons` because of the combined filesize of the package's icon fonts.

**Comment by Alhadis** [comment]
Nudging @NeutronFury54 for response.

**Comment by NeutronFury54** [comment]
Ah, I'm sorry. Fixed the issue by uninstalling some outdated files that I had downloaded in collaboration with somebody else who was working with PROS. Essentially just deleted anything on the computer related to pros then re-installed.
