### ISSUE TITLE
tsx.snap mjs.snap and ts.snap icons should match js.snap icon

### ISSUE THREAD

**Issue by brandonkal** [file-icons/atom#789]
Only js.snap files have the Jest icon. I would like to see this for all Jest snapshots.
I would contribute the fix, but it is not clear how that as done from a quick look.

**Comment by Alhadis** [comment]
Currently, the Atom package is the SSOT for icons and filetype-mappings, which are imported by the VSCode port. I've moved the issue here since it affects both packages; sorry for the confusion. 😞

Eventually, I hope to have all icon-styles and filetype-mappings drawn from a single repository, and the process for submitting updates will hopefully be a lot easier for contributors (not to mention maintainers...)
