### ISSUE TITLE
Valve icon and extension

### ISSUE THREAD

**Issue by Wanty5883** [file-icons/atom#799]
Would be very nice to add some Valve Source Engine file support.
Unfortunately there isn't much icon around for those file type.

```
BSP   - Binary Space Partition    - .bsp
VPK   - Valve Package             - .vpk .vtfx
VMT   - Valve Material Format     - .vmt
VTF   - Valve Texture Format      - .vtf
VMF   - Valve Map Format          - .vmf
RES   - Resource List             - .res
```

As they are specific files to Valve game engine, it would be a good idea to keep the Valve logo and put file extension beside it ?
I made a little example (poorly made) so you might get a better idea of what I have in mind.

![Valve-source-logo](https://user-images.githubusercontent.com/36901782/74190167-321cd100-4c52-11ea-873a-3e82cbe0109c.png)

Also thanks for this Atom package. Helps a lot. I wish could contribute myself adding more icon and new file extension. I was reading the different readme but I didn't catch what to do next adding content to the project.

**Comment by Alhadis** [comment]
The device in the [Source logo](https://upload.wikimedia.org/wikipedia/commons/6/67/Source_engine_logo_and_wordmark.svg) should be enough. I'll add it, but our release cycle is roughly once-a-month, so it wouldn't

> I wish could contribute myself adding more icon and new file extension. I was reading the different readme but I didn't catch what to do next adding content to the project.

See [`CONTRIBUTING.md`](https://github.com/file-icons/atom/blob/master/CONTRIBUTING.md). However, adding an icon is a procedure I prefer to handle myself, as most SVGs in the wild need touching-up to work as an icon. I also make a point of eliminating excess geometry in the process, which requires a certain attention to detail (as well as above-average competence with graphics software). To use this as an example:

![cmp](https://user-images.githubusercontent.com/2346707/74206420-769a8200-4ccf-11ea-960a-f27a2549bddb.gif)

Even if users have the editing skill, I don't expect them to have the time and/or patience needed to clean up some of the more extreme cases (such as Lerna's icon):

![cmp2](https://user-images.githubusercontent.com/2346707/74206661-76e74d00-4cd0-11ea-9cd5-1c72d5d654d1.gif)

The difficulties of these procedures are largely why I encourage people to submit a request, rather than a PR, since I'll need to optimise the icon anyway. Hence I've never written up a contribution guide for adding an icon.

**Comment by Wanty5883** [comment]
Well having the name beside it would be really handy. Most of the time in Source Engine folder files are mixed up. So having file extension on the icon would help a lot

**Comment by Alhadis** [comment]
We use colour variations to distinguish different formats with the same icon. Putting the extension in the icon itself isn't a good design choice, since it adds visual clutter and repeats what's already visible in the filename anyway.

I just finished adding the filetype mappings, so you'll see the colours with the next package release:

~~~cson
"Valve Source Engine":
	icon: "source"
	match: [
		[".bsp", "medium-orange", alias: "Binary Space Partition", signature: /^VBSP/]
		[".vpk", "medium-red", alias: /^Valve (Package|Pak)$/i, signature: /^4\x12\xAAU./]
		[".vtfx", "dark-red", signature: /^VTFX/]
		[".vmt", "medium-blue", alias: "Valve Material Type", scope: "vmt"]
		[".vtf", "dark-blue", alias: /^Valve Texture (File|Format)$/i, signature: /^VTF\0|^\0FTV/]
		[".vmf", "medium-maroon", alias: /^Valve Map (File|Format)$/i, uses: "XML"]
		[".res", "medium-cyan", alias: /^Resource List$/i]
	]
~~~

**Comment by Wanty5883** [comment]
Awesome ! 
Should I create more issues to list some file name, extension, icons in the future ?
I mess around video game modding, so I do see various file type. I'd be glad to help on this project

Thanks for your fast response !

**Comment by Alhadis** [comment]
Yep, go nuts.
