### ISSUE TITLE
Styling conflict with `tool-bar-atom` package

### ISSUE THREAD

**Issue by Macko-py** [file-icons/atom#857]
When I toggle the icons, the toolbar provided by Atom Toolbar is messed up and some of the icons in the toolbar are thicker or just a square. I don't know why this happens but I hope it's fixed soon. Apart from that, great extension, I've been using it since I downloaded Atom.

<table align="center">
<tr><td valign="top"><details><summary><b>Without extension:</b></summary><img src="https://user-images.githubusercontent.com/82177845/135703750-3b0c01d5-1370-4466-b516-665e1275e2fc.png" alt="Figure 1" /></details></td><td valign="top"><details><summary><b>With extension:</b></summary><img src="https://user-images.githubusercontent.com/82177845/135703767-6af69349-ab9d-4f8f-8aa5-fe2978853693.png" alt="Figure 2" /></details></td></tr></table>

**Comment by Alhadis** [comment]
Is [this](https://atom.io/packages/atom-toolbar) the package you're referring to? It hasn't been updated in _maaaaaaaaaaaany_ years, and I'm surprised it's even working for you. 🤔 Hell, when I install it, I don't see anything resembling a toolbar:

<div align="center"><img width="400" src="https://user-images.githubusercontent.com/2346707/135704744-a9efeccc-8d96-4081-8564-eb5c2f4cf4c0.png" alt="Figure 1" /></div>

… which brings me to my next question: what version of Atom are you running? Also, what packages do you have installed? If you're unsure where to gather this intel, run this from the terminal:

~~~console
$ atom --version
Atom    : 1.58.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1

$ apm ls -ib
file-icons@2.1.47
atom-toolbar@0.1.6
⋮
~~~

**Comment by Macko-py** [comment]
Your toolbar isn't working because  the atom-toolbar package itself only ads the functionality, to be able to show the toolbar you need to install one that adds the functions.
![image](https://user-images.githubusercontent.com/82177845/135719714-ba2a9ac8-becd-4f7e-9ed1-4b9bde6a3d11.png)
(also thanks for the terminal commands it was very helpful)

**Comment by Alhadis** [comment]
> Your toolbar isn't working because the atom-toolbar package itself only ads the functionality

Actually, it wasn't working because I had the wrong package. 😉 The correct name is [`tool-bar-atom`](https://atom.io/packages/tool-bar-atom) and/or [`tool-bar`](https://atom.io/packages/tool-bar).

I haven't installed most of those other packages, but what I'm seeing so far looks fine in `atom-light-ui` (my usual theme), but botched in `seti-ui`:

<blockquote><h3>Atom Light UI</h3><img src="https://user-images.githubusercontent.com/2346707/135723344-c9f2ccfc-1a5c-4dd2-b7ad-91fc4174ef25.png" alt="Figure 1: Atom Light UI" width="800" />
<h3>Seti UI</h3><img src="https://user-images.githubusercontent.com/2346707/135723363-168acbff-afd6-4aec-81ed-a2d50bc13928.png" alt="Figure 2: Seti UI" width="800" /></blockquote>

This leads me to believe there's another package (or theme) interfering with the icon styling. Could I trouble you to bring up the inspector tools for me, and inspect the styling applied to a botched icon?

<div align="center"><img width="400" src="https://user-images.githubusercontent.com/2346707/135723892-ef285e44-cd69-4dbb-afee-e3259b096244.png" alt="Figure 3" /></div>

After clicking on the guilty `<style>` tag (step 2 above), you should see the `<style />` element highlighted in the DOM tree, with a `source-path` attribute hopefully pointing to the file inside the responsible package. For example:

<img src="https://user-images.githubusercontent.com/2346707/135724073-88aef295-38b3-411b-9800-f863ac911770.png" alt="Figure 4" width="610" />

**Comment by Macko-py** [comment]
You're right! I did what you said and it displayed this:
![image](https://user-images.githubusercontent.com/82177845/135726563-c5b583e2-9c07-4107-9f3c-1affd05dc19f.png)

I thought, "that's weird, isn't that the tool-bar package?", so I disabled it and then enabled it again and suddenly it got fixed!
(I also tried changing themes before but that didn't work)

Thank you *very* much for your time and for your great toolbar!

**Comment by Alhadis** [comment]
You might want to file an issue at the tool-bar package's [repository upstream](https://github.com/atom-community/tool-bar). This package only supplies icons and some intelligent filetype detection under-the-hood. 😉

In any case, there's nothing else I can do on my end to ameliorate this, so I'm closing this. Feel free to let me know if you need help with something. 👍
